PRAGMA foreign_keys = ON;

CREATE TABLE clothing(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  cloth_type VARCHAR(64) NOT NULL, 
  filename VARCHAR(64) NOT NULL
);

CREATE TABLE laundry(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  cloth_type VARCHAR(64) NOT NULL, 
  filename VARCHAR(64) NOT NULL
);