PRAGMA foreign_keys = ON;

CREATE TABLE locations(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  location VARCHAR(64) NOT NULL, 
  capacity INTEGER(32) NOT NULL,
  max_capacity INTEGER(32) NOT NULL
);

